# -*- coding: utf-8 -*-
"""smart_plantation_disease_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plVfd7bAdHwscZcsSP02EzynokJRnWZL
"""

# Check current directory and list files
import os
print("Current directory:", os.getcwd())
print("\nContents of current directory:")
!ls -la

# Check if dataset exists
print("\nChecking for dataset:")
if os.path.exists("/content/new-plant-diseases-dataset"):
    print("✅ Dataset found at /content/new-plant-diseases-dataset")
    !ls -la /content/new-plant-diseases-dataset
else:
    print("❌ Dataset not found. We need to download it.")

# Download the dataset
print("Downloading dataset...")
!kaggle datasets download -d vipoooool/new-plant-diseases-dataset

print("\n✅ Download complete! Now extracting...")

# Create directory and extract
!mkdir -p /content/new-plant-diseases-dataset
!unzip -q new-plant-diseases-dataset.zip -d /content/new-plant-diseases-dataset

print("\n✅ Extraction complete!")

# Clean up the zip file to save space
!rm new-plant-diseases-dataset.zip

print("\n📁 Checking downloaded files:")
!ls -la /content/new-plant-diseases-dataset

# Let's explore the dataset structure
import os

base_path = "/content/new-plant-diseases-dataset"
print("Exploring dataset structure...\n")

# List all items in the base directory
items = os.listdir(base_path)
print(f"Items in base directory: {items}\n")

# Check each folder to find train and valid directories
for item in items:
    item_path = os.path.join(base_path, item)
    if os.path.isdir(item_path):
        print(f"\n📁 Checking folder: {item}")
        print(f"Contents of {item}:")
        try:
            contents = os.listdir(item_path)
            for content in contents[:5]:  # Show first 5 items
                print(f"  - {content}")
            if len(contents) > 5:
                print(f"  ... and {len(contents)-5} more")
        except:
            print("  ⚠️ Cannot list contents")

# Also check specifically for train/valid folders
print("\n" + "="*50)
print("🔍 Searching for 'train' and 'valid' folders:")
for root, dirs, files in os.walk(base_path):
    if 'train' in dirs:
        print(f"✅ Found 'train' at: {root}")
    if 'valid' in dirs:
        print(f"✅ Found 'valid' at: {root}")
    if 'val' in dirs:
        print(f"✅ Found 'val' at: {root}")

# Set the correct paths based on the search results
base_path = "/content/new-plant-diseases-dataset"

# Path to the augmented dataset (lowercase 'new' version)
dataset_path = os.path.join(base_path, "new plant diseases dataset(augmented)", "New Plant Diseases Dataset(Augmented)")

# Set train and validation paths
train_dir = os.path.join(dataset_path, "train")
valid_dir = os.path.join(dataset_path, "valid")

print("="*50)
print("✅ Paths configured:")
print(f"Base path: {base_path}")
print(f"Dataset path: {dataset_path}")
print(f"Train path: {train_dir}")
print(f"Validation path: {valid_dir}")
print("="*50)

# Verify the paths exist
print("\n🔍 Verifying paths...")

if os.path.exists(train_dir):
    print(f"✅ Train directory EXISTS")
    # Count classes in train
    classes = os.listdir(train_dir)
    print(f"📊 Number of classes in train: {len(classes)}")
    print(f"First 5 classes: {classes[:5]}")
else:
    print(f"❌ Train directory NOT found at: {train_dir}")

if os.path.exists(valid_dir):
    print(f"\n✅ Validation directory EXISTS")
    # Count classes in validation
    valid_classes = os.listdir(valid_dir)
    print(f"📊 Number of classes in validation: {len(valid_classes)}")
    print(f"First 5 validation classes: {valid_classes[:5]}")
else:
    print(f"❌ Validation directory NOT found at: {valid_dir}")

# Check if train and validation have same classes
if os.path.exists(train_dir) and os.path.exists(valid_dir):
    train_classes_set = set(classes)
    valid_classes_set = set(valid_classes)

    if train_classes_set == valid_classes_set:
        print(f"\n✅ Train and validation have the SAME {len(train_classes_set)} classes")
    else:
        print(f"\n⚠️ Train and validation have DIFFERENT classes")
        print(f"Only in train: {train_classes_set - valid_classes_set}")
        print(f"Only in valid: {valid_classes_set - train_classes_set}")

# Import all required libraries
import os
import random
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import tensorflow as tf

print("✅ All libraries imported successfully!")

# Set image size
IMG_SIZE = 224

# Get class names
train_dir = "/content/new-plant-diseases-dataset/new plant diseases dataset(augmented)/New Plant Diseases Dataset(Augmented)/train"
class_names = sorted(os.listdir(train_dir))
NUM_CLASSES = len(class_names)
print(f"Total classes: {NUM_CLASSES}")
print(f"First 5 classes: {class_names[:5]}")

# Display sample images from random classes
plt.figure(figsize=(15, 10))
for i in range(9):  # Show 9 images
    # Pick random class
    random_class = random.choice(class_names)
    class_path = os.path.join(train_dir, random_class)

    # Pick random image from that class
    images = os.listdir(class_path)
    if len(images) > 0:
        random_image = random.choice(images)
        img_path = os.path.join(class_path, random_image)

        # Load and display image
        img = Image.open(img_path)

        plt.subplot(3, 3, i+1)
        plt.imshow(img)
        # Clean up the class name for display
        display_name = random_class.replace('___', ' - ').replace('_', ' ')
        plt.title(f"{display_name}", fontsize=8)
        plt.axis('off')

plt.suptitle("Sample Images from Different Classes", fontsize=16)
plt.tight_layout()
plt.show()

# Check image dimensions of a sample
sample_class = class_names[0]
sample_image_name = os.listdir(os.path.join(train_dir, sample_class))[0]
sample_img_path = os.path.join(train_dir, sample_class, sample_image_name)
sample_img = Image.open(sample_img_path)

print(f"\n📸 Sample image details:")
print(f"Class: {sample_class}")
print(f"Image filename: {sample_image_name}")
print(f"Image dimensions: {sample_img.size}")
print(f"Image mode: {sample_img.mode}")

# Count images per class
class_counts = []
class_names_list = []

print("📊 Counting images per class...")
print("-" * 50)

for class_name in class_names:
    class_path = os.path.join(train_dir, class_name)
    num_images = len(os.listdir(class_path))
    class_counts.append(num_images)
    class_names_list.append(class_name)
    print(f"{class_name[:40]:<40} : {num_images:5d} images")

# Plot distribution
plt.figure(figsize=(12, 12))
plt.barh(class_names_list, class_counts)
plt.xlabel('Number of Images')
plt.title('Class Distribution in Training Set')
plt.tight_layout()
plt.show()

print("\n📈 Distribution Statistics:")
print(f"Total images: {sum(class_counts)}")
print(f"Average images per class: {np.mean(class_counts):.0f}")
print(f"Minimum images: {np.min(class_counts)}")
print(f"Maximum images: {np.max(class_counts)}")
print(f"Standard deviation: {np.std(class_counts):.0f}")

# Check if balanced
if np.max(class_counts) / np.min(class_counts) < 2:
    print("✅ Dataset is well-balanced!")
else:
    print("⚠️ Dataset has some imbalance (max/min ratio > 2)")

# Import required libraries
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Set parameters
IMG_SIZE = 224  # MobileNetV2 expects 224x224
BATCH_SIZE = 32

# Data augmentation for training (as shown in your screenshots)
train_datagen = ImageDataGenerator(
    rescale=1./255,           # Normalize pixel values to [0,1]
    rotation_range=20,         # Random rotation (±20 degrees)
    width_shift_range=0.2,     # Horizontal shift
    height_shift_range=0.2,    # Vertical shift
    shear_range=0.2,           # Shearing transformations
    zoom_range=0.2,            # Random zoom
    horizontal_flip=True,      # Flip horizontally
    fill_mode='nearest'        # Strategy for filling new pixels
)

# Validation data - only rescaling (no augmentation)
valid_datagen = ImageDataGenerator(rescale=1./255)

print("✅ Data generators created")
print(f"Image size: {IMG_SIZE}x{IMG_SIZE}")
print(f"Batch size: {BATCH_SIZE}")
print("\n📊 Augmentation techniques applied:")
print("  • Rotation range: 20°")
print("  • Width/height shift: 20%")
print("  • Shear range: 0.2")
print("  • Zoom range: 20%")
print("  • Horizontal flip: Yes")

# Create training generator
print("🔄 Creating training generator...")
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True
)

print("\n🔄 Creating validation generator...")
validation_generator = valid_datagen.flow_from_directory(
    valid_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

print("\n" + "="*50)
print("✅ GENERATORS READY")
print("="*50)
print(f"Training samples: {train_generator.samples}")
print(f"Validation samples: {validation_generator.samples}")
print(f"Number of classes: {train_generator.num_classes}")

# Get a sample batch to check shape
sample_batch, sample_labels = next(train_generator)
print(f"\n📦 Batch shape: {sample_batch.shape}")
print(f"📦 Labels shape: {sample_labels.shape}")

# Save class indices for later use
class_indices = train_generator.class_indices
# Create reverse mapping (index -> class name)
class_names = {v: k for k, v in class_indices.items()}
print(f"\n📋 First 5 class mappings:")
for i in range(5):
    print(f"  Index {i}: {class_names[i]}")

# Import required libraries for model building
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.applications import MobileNetV2

print("✅ Libraries imported")
print(f"TensorFlow version: {tf.__version__}")

# Set parameters
IMG_SIZE = 224
NUM_CLASSES = 38
INPUT_SHAPE = (IMG_SIZE, IMG_SIZE, 3)

# Load pre-trained MobileNetV2
print("\n🔄 Loading MobileNetV2 pre-trained on ImageNet...")
base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=INPUT_SHAPE
)

print("✅ Base model loaded successfully!")
print(f"Base model architecture: {base_model.name}")
print(f"Base model output shape: {base_model.output_shape}")

# First, freeze the base model layers (they will not be trained initially)
base_model.trainable = False

print("✅ Base model frozen")
print(f"Trainable weights: {len(base_model.trainable_weights)}")

# Build the complete model as shown in your screenshot
inputs = keras.Input(shape=INPUT_SHAPE)
print(f"✓ Input layer: {inputs.shape}")

# Pass through base model
x = base_model(inputs, training=False)
print(f"✓ After MobileNetV2: {x.shape}")

# Add Global Average Pooling
x = layers.GlobalAveragePooling2D()(x)
print(f"✓ After GlobalAvgPooling: {x.shape}")

# Add Dropout (0.35 as per your screenshot)
x = layers.Dropout(0.35)(x)
print(f"✓ After Dropout (0.35): {x.shape}")

# Add Dense layer with 256 units
x = layers.Dense(256, activation='relu')(x)
print(f"✓ After Dense (256): {x.shape}")

# Add another Dropout (0.25 as per your screenshot)
x = layers.Dropout(0.25)(x)
print(f"✓ After Dropout (0.25): {x.shape}")

# Output layer with 38 classes (softmax activation)
outputs = layers.Dense(NUM_CLASSES, activation='softmax')(x)
print(f"✓ Output layer: {outputs.shape}")

# Create the model
model = keras.Model(inputs, outputs, name="mobilenetv2_plant_disease_classifier")

print("\n" + "="*50)
print("✅ MODEL BUILT SUCCESSFULLY!")
print("="*50)

# Display model summary
model.summary()

# Configure transfer learning strategy - unfreeze last 10 layers for fine-tuning
N_LAST_LAYERS = 10

# Unfreeze the base model
base_model.trainable = True

# Freeze all layers first
for layer in base_model.layers:
    layer.trainable = False

# Unfreeze last N layers
for layer in base_model.layers[-N_LAST_LAYERS:]:
    layer.trainable = True

print(f"✅ Transfer learning strategy configured")
print(f"✓ Unfroze last {N_LAST_LAYERS} layers of MobileNetV2")
print(f"✓ All other layers remain frozen")

# Count trainable parameters
trainable_count = np.sum([np.prod(w.shape) for w in model.trainable_weights])
non_trainable_count = np.sum([np.prod(w.shape) for w in model.non_trainable_weights])

print(f"\n📊 Parameter distribution after fine-tuning configuration:")
print(f"   Trainable parameters: {trainable_count:,}")
print(f"   Non-trainable parameters: {non_trainable_count:,}")
print(f"   Total parameters: {trainable_count + non_trainable_count:,}")

# Compile model with appropriate settings (as per your screenshot)
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),  # Low learning rate for fine-tuning
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print("✅ Model compiled successfully!")
print(f"✓ Optimizer: Adam (lr=1e-4)")
print(f"✓ Loss function: Categorical Crossentropy")
print(f"✓ Metrics: Accuracy")

# Define training callbacks (as per your screenshot)
callbacks = [
    # Save best model based on validation accuracy
    keras.callbacks.ModelCheckpoint(
        "/content/mobilenetv2_best.keras",
        monitor="val_accuracy",
        save_best_only=True,
        verbose=1
    ),
    # Reduce learning rate when validation loss plateaus
    keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        verbose=1,
        min_lr=1e-7
    ),
    # Stop training if no improvement
    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=6,
        restore_best_weights=True,
        verbose=1
    )
]

print("✅ Callbacks configured:")
print("  1. ModelCheckpoint - Saves best model")
print("  2. ReduceLROnPlateau - Adjusts learning rate (factor=0.5, patience=3)")
print("  3. EarlyStopping - Prevents overfitting (patience=6)")

# Set number of epochs
EPOCHS = 5  # As shown in your screenshot (0-40 on x-axis)

print("🚀 Starting model training...")
print(f"✓ Training samples: {train_generator.samples}")
print(f"✓ Validation samples: {validation_generator.samples}")
print(f"✓ Batch size: {BATCH_SIZE}")
print(f"✓ Steps per epoch: {train_generator.samples // BATCH_SIZE}")
print(f"✓ Validation steps: {validation_generator.samples // BATCH_SIZE}")
print(f"✓ Epochs: {EPOCHS}")
print("="*50)

# Train the model
history = model.fit(
    train_generator,
    epochs=EPOCHS,
    validation_data=validation_generator,
    callbacks=callbacks,
    verbose=1  # Show progress bars
)

print("\n✅ Training completed!")

from tensorflow import keras
model = keras.models.load_model('/content/mobilenetv2_best.keras')

# If you loaded data using tensorflow datasets
import tensorflow as tf

# Example for built-in datasets
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

# Normalize if needed
x_test = x_test.astype('float32') / 255.0

# Create test dataset
test_data = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(32)

import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
import os

# Load your trained model
model = keras.models.load_model('/content/mobilenetv2_best.keras')

# Check your project structure - where are your plant disease images?
# Common structures:
# /content/plant_disease_dataset/test/
# /content/PlantVillage/
# /content/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid/

# List directories to find your data
print("Current directory contents:")
!ls -la

# Try to find your dataset
print("\nLooking for dataset directories:")
!find . -type d -name "*test*" -o -name "*valid*" -o -name "*val*" 2>/dev/null | head -20

from tensorflow.keras.preprocessing import image_dataset_from_directory
from tensorflow import keras

# Load model
model = keras.models.load_model('/content/mobilenetv2_best.keras')

# Use validation folder (has all 38 classes)
test_data = image_dataset_from_directory(
    '/content/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid',
    image_size=(224, 224),
    batch_size=32,
    label_mode='categorical',
    shuffle=False
)

# Get class names
class_names = test_data.class_names
print(f"Found {len(class_names)} classes: {class_names[:5]}...")  # Show first 5

# Evaluate
loss, accuracy = model.evaluate(test_data)
print(f"\nTest Accuracy: {accuracy*100:.2f}%")

import os

# Show current directory contents
print("Current folder:")
!pwd
print("\nFiles and folders here:")
!ls -la

# Quick search for test folders
print("\nLooking for test folders:")
!find . -type d -name "test" -o -name "valid" -o -name "val" 2>/dev/null | head -10

from tensorflow.keras.preprocessing import image_dataset_from_directory
from tensorflow import keras

# Load model
model = keras.models.load_model('/content/mobilenetv2_best.keras')

# Load validation data with categorical labels
test_data = image_dataset_from_directory(
    '/content/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid',
    image_size=(224, 224),
    batch_size=32,
    label_mode='categorical',  # This fixes the error
    shuffle=False
)

# Evaluate
loss, accuracy = model.evaluate(test_data)
print(f"\nTest Accuracy: {accuracy*100:.2f}%")

# Show the full dataset structure
!ls -la /content/new-plant-diseases-dataset/
!ls -la /content/new-plant-diseases-dataset/New\ Plant\ Diseases\ Dataset\(Augmented\)/New\ Plant\ Diseases\ Dataset\(Augmented\)/

from tensorflow import keras
import numpy as np

# Load model
model = keras.models.load_model('/content/mobilenetv2_best.keras')

# Check model output shape
print(f"Model output shape: {model.output_shape}")
print(f"Number of classes model expects: {model.output_shape[-1]}")

import os

train_path = '/content/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train'
valid_path = '/content/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid'

# Get class names from train folder
train_classes = sorted([d for d in os.listdir(train_path) if os.path.isdir(os.path.join(train_path, d))])
print(f"Train folder has {len(train_classes)} classes")
print(f"First 5: {train_classes[:5]}")

# Get class names from valid folder
valid_classes = sorted([d for d in os.listdir(valid_path) if os.path.isdir(os.path.join(valid_path, d))])
print(f"\nValid folder has {len(valid_classes)} classes")
print(f"First 5: {valid_classes[:5]}")

# Check if they match
if train_classes == valid_classes:
    print(f"\n✅ Train and valid folders have the same {len(train_classes)} classes")
else:
    print(f"\n❌ Mismatch! Train has {len(train_classes)} classes, Valid has {len(valid_classes)} classes")

from tensorflow.keras.preprocessing import image_dataset_from_directory
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow import keras
import tensorflow as tf

# Load model
model = keras.models.load_model('/content/mobilenetv2_best.keras')

# Load test/validation data
test_data = image_dataset_from_directory(
    '/content/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid',
    image_size=(224, 224),
    batch_size=32,
    label_mode='categorical',
    shuffle=False
)

# Apply MobileNetV2 preprocessing (THIS IS CRITICAL)
test_data = test_data.map(lambda x, y: (preprocess_input(x), y))

# Evaluate
loss, accuracy = model.evaluate(test_data)
print(f"\n✅ Model Accuracy: {accuracy*100:.2f}%")

from google.colab import files
uploaded = files.upload()

from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras

# Load model (if not already loaded)
model = keras.models.load_model('/content/mobilenetv2_best.keras')

# Get class names from your validation data
from tensorflow.keras.preprocessing import image_dataset_from_directory
valid_data = image_dataset_from_directory(
    '/content/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid',
    image_size=(224, 224),
    batch_size=32,
    label_mode='categorical',
    shuffle=False
)
class_names = valid_data.class_names

# Load and test the uploaded image
img_path = 'leaf.jpg'
img = image.load_img(img_path, target_size=(224, 224))
plt.imshow(img)
plt.axis('off')
plt.show()

img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = preprocess_input(img_array)

# Predict
prediction = model.predict(img_array)
predicted_class = class_names[np.argmax(prediction[0])]
confidence = np.max(prediction[0]) * 100

print(f"\n✅ Predicted: {predicted_class}")
print(f"📊 Confidence: {confidence:.2f}%")

import os

# Create project folders
os.makedirs('/content/plantcare-api/static/uploads', exist_ok=True)
os.makedirs('/content/plantcare-api/templates', exist_ok=True)
os.makedirs('/content/plantcare-api/model', exist_ok=True)

print("✅ Folders created:")
!ls -la /content/plantcare-api/

import shutil
import os
from tensorflow.keras.preprocessing import image_dataset_from_directory
import pickle

# Copy your trained model to the project folder
shutil.copy('/content/mobilenetv2_best.keras', '/content/plantcare-api/model/')
print("✅ Model copied")

# Get and save class names
valid_path = '/content/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid'
valid_data = image_dataset_from_directory(
    valid_path,
    image_size=(224, 224),
    batch_size=32,
    shuffle=False
)
class_names = valid_data.class_names

# Save class names to file
with open('/content/plantcare-api/model/class_names.pkl', 'wb') as f:
    pickle.dump(class_names, f)

print(f"✅ Class names saved: {len(class_names)} classes")
print(f"First 5: {class_names[:5]}")

# Check files in model folder
print("\n📁 Model folder contents:")
!ls -la /content/plantcare-api/model/

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/plantcare-api/app.py
# 
# from flask import Flask, request, jsonify, render_template, session, url_for, redirect
# import os
# import numpy as np
# import tensorflow as tf
# from tensorflow.keras.models import load_model
# from tensorflow.keras.preprocessing import image
# from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
# from werkzeug.utils import secure_filename
# import pickle
# from PIL import Image
# import uuid
# 
# # Initialize Flask app
# app = Flask(__name__)
# app.secret_key = 'plantcare-ai-secret-key'  # Required for session
# app.config['UPLOAD_FOLDER'] = 'static/uploads'
# app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024  # 16MB max upload
# 
# # Ensure upload folder exists
# os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)
# 
# # Load model and class names
# print("Loading model...")
# model = load_model('model/mobilenetv2_best.keras')
# print("✅ Model loaded successfully")
# 
# with open('model/class_names.pkl', 'rb') as f:
#     class_names = pickle.load(f)
# print(f"✅ Class names loaded: {len(class_names)} classes")
# 
# def predict_image(img_path):
#     """Predict disease from image path"""
#     # Load and preprocess image
#     img = image.load_img(img_path, target_size=(224, 224))
#     img_array = image.img_to_array(img)
#     img_array = np.expand_dims(img_array, axis=0)
#     img_array = preprocess_input(img_array)
# 
#     # Predict
#     predictions = model.predict(img_array, verbose=0)
#     predicted_class_idx = np.argmax(predictions[0])
#     confidence = float(predictions[0][predicted_class_idx])
# 
#     # Get class name
#     disease_name = class_names[predicted_class_idx]
# 
#     return {
#         'disease': disease_name,
#         'confidence': confidence,
#         'confidence_percentage': round(confidence * 100, 2)
#     }
# 
# @app.route('/')
# def index():
#     """Home page"""
#     return render_template('index.html')
# 
# @app.route('/upload')
# def upload_page():
#     """Upload page"""
#     return render_template('upload.html')
# 
# @app.route('/predict', methods=['POST'])
# def predict():
#     """API endpoint for prediction"""
#     if 'file' not in request.files:
#         return jsonify({'error': 'No file uploaded'}), 400
# 
#     file = request.files['file']
#     if file.filename == '':
#         return jsonify({'error': 'No file selected'}), 400
# 
#     if file:
#         # Generate unique filename
#         filename = str(uuid.uuid4()) + '_' + secure_filename(file.filename)
#         filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
#         file.save(filepath)
# 
#         try:
#             # Make prediction
#             result = predict_image(filepath)
# 
#             # Save to session for results page
#             session['prediction'] = result
#             session['image_path'] = filepath
# 
#             return jsonify({'success': True, 'redirect': '/result'})
# 
#         except Exception as e:
#             # Clean up on error
#             if os.path.exists(filepath):
#                 os.remove(filepath)
#             return jsonify({'error': str(e)}), 500
# 
# @app.route('/result')
# def result():
#     """Results page"""
#     prediction = session.get('prediction')
#     image_path = session.get('image_path')
# 
#     if not prediction or not image_path:
#         return redirect(url_for('upload_page'))
# 
#     # Make path relative for template
#     image_relative = image_path.replace('static/', '')
# 
#     return render_template('result.html',
#                           prediction=prediction,
#                           image_path=image_relative)
# 
# @app.route('/api/classes')
# def get_classes():
#     """API endpoint to get all class names"""
#     return jsonify({'classes': class_names})
# 
# @app.route('/health')
# def health():
#     """Health check endpoint"""
#     return jsonify({'status': 'healthy', 'classes': len(class_names)})
# 
# if __name__ == '__main__':
#     app.run(debug=True, host='0.0.0.0', port=5000)

!ls -la /content/plantcare-api/app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/plantcare-api/templates/index.html
# 
# <!DOCTYPE html>
# <html lang="en">
# <head>
#     <meta charset="UTF-8">
#     <meta name="viewport" content="width=device-width, initial-scale=1.0">
#     <title>PlantCare AI - Home</title>
#     <style>
#         * {
#             margin: 0;
#             padding: 0;
#             box-sizing: border-box;
#         }
#         body {
#             font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
#             background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
#             min-height: 100vh;
#             color: white;
#         }
#         .container {
#             max-width: 1200px;
#             margin: 0 auto;
#             padding: 40px 20px;
#         }
#         .navbar {
#             display: flex;
#             justify-content: space-between;
#             align-items: center;
#             padding: 20px 0;
#         }
#         .logo {
#             font-size: 24px;
#             font-weight: bold;
#         }
#         .nav-links a {
#             color: white;
#             text-decoration: none;
#             margin-left: 30px;
#             padding: 8px 16px;
#             border-radius: 20px;
#             transition: background 0.3s;
#         }
#         .nav-links a:hover {
#             background: rgba(255,255,255,0.2);
#         }
#         .hero {
#             text-align: center;
#             padding: 80px 0;
#         }
#         .hero h1 {
#             font-size: 48px;
#             margin-bottom: 20px;
#         }
#         .hero p {
#             font-size: 20px;
#             margin-bottom: 40px;
#             opacity: 0.9;
#         }
#         .cta-button {
#             display: inline-block;
#             background: white;
#             color: #667eea;
#             padding: 15px 40px;
#             border-radius: 30px;
#             text-decoration: none;
#             font-weight: bold;
#             font-size: 18px;
#             transition: transform 0.3s;
#         }
#         .cta-button:hover {
#             transform: translateY(-3px);
#         }
#         .features {
#             display: grid;
#             grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
#             gap: 30px;
#             margin-top: 80px;
#         }
#         .feature-card {
#             background: rgba(255,255,255,0.1);
#             padding: 30px;
#             border-radius: 10px;
#             text-align: center;
#             backdrop-filter: blur(10px);
#         }
#         .feature-card h3 {
#             font-size: 24px;
#             margin-bottom: 15px;
#         }
#         .footer {
#             text-align: center;
#             padding: 40px 0;
#             margin-top: 80px;
#             border-top: 1px solid rgba(255,255,255,0.1);
#         }
#     </style>
# </head>
# <body>
#     <div class="container">
#         <nav class="navbar">
#             <div class="logo">🌱 PlantCare AI</div>
#             <div class="nav-links">
#                 <a href="/">Home</a>
#                 <a href="/upload">Upload</a>
#             </div>
#         </nav>
# 
#         <div class="hero">
#             <h1>AI-Powered Plant Disease Detection</h1>
#             <p>Upload a photo of your plant leaf and get instant disease detection with 86% accuracy</p>
#             <a href="/upload" class="cta-button">Get Started Now</a>
#         </div>
# 
#         <div class="features">
#             <div class="feature-card">
#                 <h3>🔍 Instant Detection</h3>
#                 <p>Get notified as soon as your plant shows symptoms</p>
#             </div>
#             <div class="feature-card">
#                 <h3>🎯 High Accuracy</h3>
#                 <p>86% accuracy across 38 different plant diseases</p>
#             </div>
#             <div class="feature-card">
#                 <h3>🌿 38+ Classes</h3>
#                 <p>Covering Apple, Tomato, Potato, Corn and more</p>
#             </div>
#         </div>
# 
#         <div class="footer">
#             <p>© 2025 Smart Bridge Hybridland | Empowering agriculture through AI</p>
#         </div>
#     </div>
# </body>
# </html>

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/plantcare-api/templates/upload.html
# 
# <!DOCTYPE html>
# <html lang="en">
# <head>
#     <meta charset="UTF-8">
#     <meta name="viewport" content="width=device-width, initial-scale=1.0">
#     <title>PlantCare AI - Upload</title>
#     <style>
#         * {
#             margin: 0;
#             padding: 0;
#             box-sizing: border-box;
#         }
#         body {
#             font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
#             background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
#             min-height: 100vh;
#             color: white;
#         }
#         .container {
#             max-width: 800px;
#             margin: 0 auto;
#             padding: 40px 20px;
#         }
#         .navbar {
#             display: flex;
#             justify-content: space-between;
#             align-items: center;
#             padding: 20px 0;
#         }
#         .logo {
#             font-size: 24px;
#             font-weight: bold;
#         }
#         .nav-links a {
#             color: white;
#             text-decoration: none;
#             margin-left: 30px;
#             padding: 8px 16px;
#             border-radius: 20px;
#             transition: background 0.3s;
#         }
#         .nav-links a:hover {
#             background: rgba(255,255,255,0.2);
#         }
#         .upload-container {
#             background: rgba(255,255,255,0.1);
#             backdrop-filter: blur(10px);
#             border-radius: 20px;
#             padding: 40px;
#             margin-top: 40px;
#             text-align: center;
#         }
#         .upload-area {
#             border: 3px dashed rgba(255,255,255,0.3);
#             border-radius: 20px;
#             padding: 60px 20px;
#             margin: 30px 0;
#             cursor: pointer;
#             transition: border-color 0.3s;
#         }
#         .upload-area:hover {
#             border-color: white;
#         }
#         .upload-area i {
#             font-size: 64px;
#             margin-bottom: 20px;
#             opacity: 0.8;
#         }
#         .upload-area p {
#             font-size: 18px;
#             margin-bottom: 10px;
#         }
#         .upload-area small {
#             opacity: 0.7;
#         }
#         #file-input {
#             display: none;
#         }
#         .preview-container {
#             margin: 30px 0;
#             display: none;
#         }
#         .preview-container img {
#             max-width: 300px;
#             max-height: 300px;
#             border-radius: 10px;
#             box-shadow: 0 10px 30px rgba(0,0,0,0.3);
#         }
#         .analyze-btn {
#             background: white;
#             color: #667eea;
#             border: none;
#             padding: 15px 40px;
#             border-radius: 30px;
#             font-weight: bold;
#             font-size: 18px;
#             cursor: pointer;
#             transition: transform 0.3s;
#             display: none;
#         }
#         .analyze-btn:hover {
#             transform: translateY(-3px);
#         }
#         .loading {
#             display: none;
#             margin: 30px 0;
#         }
#         .loading-spinner {
#             border: 4px solid rgba(255,255,255,0.3);
#             border-radius: 50%;
#             border-top: 4px solid white;
#             width: 40px;
#             height: 40px;
#             animation: spin 1s linear infinite;
#             margin: 0 auto 20px;
#         }
#         @keyframes spin {
#             0% { transform: rotate(0deg); }
#             100% { transform: rotate(360deg); }
#         }
#         .tips {
#             text-align: left;
#             margin-top: 40px;
#             padding: 20px;
#             background: rgba(0,0,0,0.2);
#             border-radius: 10px;
#         }
#         .tips h3 {
#             margin-bottom: 15px;
#         }
#         .tips ul {
#             list-style-type: none;
#         }
#         .tips li {
#             margin-bottom: 10px;
#             padding-left: 25px;
#             position: relative;
#         }
#         .tips li:before {
#             content: "✓";
#             position: absolute;
#             left: 0;
#             color: #4CAF50;
#         }
#     </style>
# </head>
# <body>
#     <div class="container">
#         <nav class="navbar">
#             <div class="logo">🌱 PlantCare AI</div>
#             <div class="nav-links">
#                 <a href="/">Home</a>
#                 <a href="/upload">Upload</a>
#             </div>
#         </nav>
# 
#         <div class="upload-container">
#             <h2>Upload Plant Image</h2>
#             <p>Take or upload a clear photo of the affected plant leaf</p>
# 
#             <div class="upload-area" id="upload-area">
#                 <i>📸</i>
#                 <p>Drag & Drop Image Here</p>
#                 <p>or click to browse from your device</p>
#                 <small>Supports: JPG, PNG (Max 16MB)</small>
#             </div>
# 
#             <input type="file" id="file-input" accept="image/*">
# 
#             <div class="preview-container" id="preview-container">
#                 <img id="preview-image" src="" alt="Preview">
#             </div>
# 
#             <div class="loading" id="loading">
#                 <div class="loading-spinner"></div>
#                 <p>Analyzing your plant image...</p>
#             </div>
# 
#             <button class="analyze-btn" id="analyze-btn">Analyze Image</button>
# 
#             <div class="tips">
#                 <h3>📝 Tips for Best Results</h3>
#                 <ul>
#                     <li>Take photos in good lighting</li>
#                     <li>Focus on the affected leaf area</li>
#                     <li>Keep the camera steady</li>
#                     <li>Include both healthy and diseased parts if possible</li>
#                 </ul>
#             </div>
#         </div>
#     </div>
# 
#     <script>
#         const uploadArea = document.getElementById('upload-area');
#         const fileInput = document.getElementById('file-input');
#         const previewContainer = document.getElementById('preview-container');
#         const previewImage = document.getElementById('preview-image');
#         const analyzeBtn = document.getElementById('analyze-btn');
#         const loading = document.getElementById('loading');
# 
#         // Click on upload area triggers file input
#         uploadArea.addEventListener('click', () => {
#             fileInput.click();
#         });
# 
#         // Drag and drop handlers
#         uploadArea.addEventListener('dragover', (e) => {
#             e.preventDefault();
#             uploadArea.style.borderColor = 'white';
#         });
# 
#         uploadArea.addEventListener('dragleave', (e) => {
#             e.preventDefault();
#             uploadArea.style.borderColor = 'rgba(255,255,255,0.3)';
#         });
# 
#         uploadArea.addEventListener('drop', (e) => {
#             e.preventDefault();
#             uploadArea.style.borderColor = 'rgba(255,255,255,0.3)';
#             const files = e.dataTransfer.files;
#             if (files.length > 0) {
#                 fileInput.files = files;
#                 handleFileSelect(files[0]);
#             }
#         });
# 
#         // File selection handler
#         fileInput.addEventListener('change', (e) => {
#             if (e.target.files.length > 0) {
#                 handleFileSelect(e.target.files[0]);
#             }
#         });
# 
#         function handleFileSelect(file) {
#             if (file.type.startsWith('image/')) {
#                 const reader = new FileReader();
#                 reader.onload = (e) => {
#                     previewImage.src = e.target.result;
#                     previewContainer.style.display = 'block';
#                     analyzeBtn.style.display = 'inline-block';
#                     uploadArea.style.display = 'none';
#                 };
#                 reader.readAsDataURL(file);
#             } else {
#                 alert('Please select an image file');
#             }
#         }
# 
#         // Analyze button handler
#         analyzeBtn.addEventListener('click', async () => {
#             const file = fileInput.files[0];
#             if (!file) return;
# 
#             // Show loading
#             loading.style.display = 'block';
#             analyzeBtn.style.display = 'none';
# 
#             // Create form data
#             const formData = new FormData();
#             formData.append('file', file);
# 
#             try {
#                 // Send to server
#                 const response = await fetch('/predict', {
#                     method: 'POST',
#                     body: formData
#                 });
# 
#                 const data = await response.json();
# 
#                 if (data.success) {
#                     // Redirect to results page
#                     window.location.href = data.redirect;
#                 } else {
#                     alert('Error: ' + data.error);
#                     loading.style.display = 'none';
#                     analyzeBtn.style.display = 'inline-block';
#                 }
#             } catch (error) {
#                 alert('Error uploading file');
#                 loading.style.display = 'none';
#                 analyzeBtn.style.display = 'inline-block';
#             }
#         });
#     </script>
# </body>
# </html>

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/plantcare-api/templates/result.html
# 
# <!DOCTYPE html>
# <html lang="en">
# <head>
#     <meta charset="UTF-8">
#     <meta name="viewport" content="width=device-width, initial-scale=1.0">
#     <title>PlantCare AI - Results</title>
#     <style>
#         * {
#             margin: 0;
#             padding: 0;
#             box-sizing: border-box;
#         }
#         body {
#             font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
#             background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
#             min-height: 100vh;
#             color: white;
#         }
#         .container {
#             max-width: 1000px;
#             margin: 0 auto;
#             padding: 40px 20px;
#         }
#         .navbar {
#             display: flex;
#             justify-content: space-between;
#             align-items: center;
#             padding: 20px 0;
#         }
#         .logo {
#             font-size: 24px;
#             font-weight: bold;
#         }
#         .nav-links a {
#             color: white;
#             text-decoration: none;
#             margin-left: 30px;
#             padding: 8px 16px;
#             border-radius: 20px;
#             transition: background 0.3s;
#         }
#         .nav-links a:hover {
#             background: rgba(255,255,255,0.2);
#         }
#         .result-container {
#             background: rgba(255,255,255,0.1);
#             backdrop-filter: blur(10px);
#             border-radius: 20px;
#             padding: 40px;
#             margin-top: 40px;
#         }
#         .result-header {
#             text-align: center;
#             margin-bottom: 40px;
#         }
#         .result-header h2 {
#             font-size: 32px;
#             margin-bottom: 10px;
#         }
#         .result-content {
#             display: grid;
#             grid-template-columns: 1fr 1fr;
#             gap: 40px;
#             align-items: start;
#         }
#         .image-section {
#             text-align: center;
#         }
#         .image-section img {
#             max-width: 100%;
#             border-radius: 10px;
#             box-shadow: 0 10px 30px rgba(0,0,0,0.3);
#         }
#         .image-section h3 {
#             margin: 20px 0 10px;
#         }
#         .info-section {
#             background: rgba(0,0,0,0.2);
#             padding: 30px;
#             border-radius: 10px;
#         }
#         .disease-name {
#             font-size: 28px;
#             font-weight: bold;
#             margin-bottom: 20px;
#             color: #4CAF50;
#         }
#         .confidence-bar {
#             margin: 20px 0;
#         }
#         .confidence-label {
#             display: flex;
#             justify-content: space-between;
#             margin-bottom: 5px;
#         }
#         .bar {
#             height: 20px;
#             background: rgba(255,255,255,0.2);
#             border-radius: 10px;
#             overflow: hidden;
#         }
#         .bar-fill {
#             height: 100%;
#             background: linear-gradient(90deg, #4CAF50, #8BC34A);
#             border-radius: 10px;
#         }
#         .recommendations {
#             margin-top: 30px;
#         }
#         .recommendations h4 {
#             font-size: 20px;
#             margin-bottom: 15px;
#         }
#         .recommendations ul {
#             list-style-type: none;
#         }
#         .recommendations li {
#             margin-bottom: 10px;
#             padding-left: 25px;
#             position: relative;
#         }
#         .recommendations li:before {
#             content: "🌿";
#             position: absolute;
#             left: 0;
#         }
#         .action-buttons {
#             margin-top: 40px;
#             text-align: center;
#         }
#         .btn {
#             display: inline-block;
#             background: white;
#             color: #667eea;
#             padding: 12px 30px;
#             border-radius: 30px;
#             text-decoration: none;
#             font-weight: bold;
#             margin: 0 10px;
#             transition: transform 0.3s;
#         }
#         .btn:hover {
#             transform: translateY(-3px);
#         }
#         .btn-secondary {
#             background: transparent;
#             border: 2px solid white;
#             color: white;
#         }
#         .plant-type {
#             font-size: 18px;
#             margin-bottom: 10px;
#             opacity: 0.9;
#         }
#     </style>
# </head>
# <body>
#     <div class="container">
#         <nav class="navbar">
#             <div class="logo">🌱 PlantCare AI</div>
#             <div class="nav-links">
#                 <a href="/">Home</a>
#                 <a href="/upload">Upload</a>
#             </div>
#         </nav>
# 
#         <div class="result-container">
#             <div class="result-header">
#                 <h2>Analysis Complete</h2>
#                 <p>Here's what we found in your plant image</p>
#             </div>
# 
#             <div class="result-content">
#                 <div class="image-section">
#                     <img src="{{ url_for('static', filename=image_path) }}" alt="Uploaded leaf">
#                     <h3>Uploaded Image</h3>
#                 </div>
# 
#                 <div class="info-section">
#                     {% set plant_parts = prediction.disease.split('___') %}
#                     {% set plant_type = plant_parts[0] %}
#                     {% set disease_name = plant_parts[1].replace('_', ' ') %}
# 
#                     <div class="plant-type">Plant: {{ plant_type }}</div>
#                     <div class="disease-name">{{ disease_name }}</div>
# 
#                     <div class="confidence-bar">
#                         <div class="confidence-label">
#                             <span>Confidence</span>
#                             <span>{{ prediction.confidence_percentage }}%</span>
#                         </div>
#                         <div class="bar">
#                             <div class="bar-fill" style="width: {{ prediction.confidence_percentage }}%"></div>
#                         </div>
#                     </div>
# 
#                     <div class="recommendations">
#                         <h4>🌱 Recommendations</h4>
#                         <ul>
#                             {% if 'healthy' in prediction.disease.lower() %}
#                                 <li>Your plant looks healthy! Continue regular care</li>
#                                 <li>Maintain proper watering schedule</li>
#                                 <li>Ensure adequate sunlight</li>
#                             {% else %}
#                                 <li>Remove affected leaves to prevent spread</li>
#                                 <li>Consider organic fungicides or pesticides</li>
#                                 <li>Improve air circulation around plant</li>
#                                 <li>Monitor nearby plants for symptoms</li>
#                             {% endif %}
#                             <li>Control temperature and humidity</li>
#                             <li>Ensure proper soil conditions</li>
#                         </ul>
#                     </div>
#                 </div>
#             </div>
# 
#             <div class="action-buttons">
#                 <a href="/upload" class="btn">Analyze Another Image</a>
#                 <a href="/" class="btn btn-secondary">Back to Home</a>
#             </div>
#         </div>
#     </div>
# </body>
# </html>

!ls -la /content/plantcare-api/templates/

# Commented out IPython magic to ensure Python compatibility.
# Install Flask if not already installed
!pip install flask flask-ngrok

# Change to project directory
# %cd /content/plantcare-api

# Run the Flask app
!python app.py

# Commented out IPython magic to ensure Python compatibility.
from google.colab import files
import os

# Go to content directory
# %cd /content

# Check if the folder exists
print("Checking if plantcare-api folder exists:")
!ls -la | grep plantcare

# Create zip file properly
!zip -r plantcare-api.zip plantcare-api/

# Verify zip was created
print("\nChecking if zip was created:")
!ls -la plantcare-api.zip

# Download
files.download('plantcare-api.zip')